#! /usr/bin/env bash

# When run, this program will output a list of arguments which are necessary to
# load the GHC library component into GHCi. The program is used by `ghcide` in
# order to automatically set up the correct GHC API session for a project.
args="$(TERM=dumb CABFLAGS=-v0 $PWD/hadrian/build.cabal.sh tool-args -q -j --build-root=.hie-bios --flavour=ghc-in-ghci) -ighc ghc/Main.hs -I/home/matt/ghc/compiler"
echo "$args" | tr " " "\n" > $HIE_BIOS_OUTPUT

